Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  4.0.167.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'MultiPurposeConstituentTileViewDataFormCONSTITUENTINFO' data form
''' </summary>
Partial Public Class [MultiPurposeConstituentTileViewDataFormCONSTITUENTINFOUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.UIModel

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _id As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
    Private WithEvents _lineone As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _linetwo As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _linethree As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _linefour As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _linefive As Global.Blackbaud.AppFx.UIModeling.Core.StringField

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.167.0")> _
    Public Sub New()
        MyBase.New()

        _id = New Global.Blackbaud.AppFx.UIModeling.Core.GuidField
        _lineone = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _linetwo = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _linethree = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _linefour = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _linefive = New Global.Blackbaud.AppFx.UIModeling.Core.StringField

        '
        '_id
        '
        _id.Name = "ID"
        _id.Caption = "ID"
        _id.DBReadOnly = True
        Me.Fields.Add(_id)
        '
        '_lineone
        '
        _lineone.Name = "LINEONE"
        _lineone.Caption = "Line One"
        _lineone.DBReadOnly = True
        Me.Fields.Add(_lineone)
        '
        '_linetwo
        '
        _linetwo.Name = "LINETWO"
        _linetwo.Caption = "Line Two"
        _linetwo.DBReadOnly = True
        Me.Fields.Add(_linetwo)
        '
        '_linethree
        '
        _linethree.Name = "LINETHREE"
        _linethree.Caption = "Line Three"
        _linethree.DBReadOnly = True
        Me.Fields.Add(_linethree)
        '
        '_linefour
        '
        _linefour.Name = "LINEFOUR"
        _linefour.Caption = "Line Four"
        _linefour.DBReadOnly = True
        Me.Fields.Add(_linefour)
        '
        '_linefive
        '
        _linefive.Name = "LINEFIVE"
        _linefive.Caption = "Line Five"
        _linefive.DBReadOnly = True
        Me.Fields.Add(_linefive)

		OnCreated()

    End Sub
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.167.0")> _
    Public ReadOnly Property [ID]() As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
        Get
            Return _id
        End Get
    End Property
    
    ''' <summary>
    ''' Line One
    ''' </summary>
    <System.ComponentModel.Description("Line One")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.167.0")> _
    Public ReadOnly Property [LINEONE]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _lineone
        End Get
    End Property
    
    ''' <summary>
    ''' Line Two
    ''' </summary>
    <System.ComponentModel.Description("Line Two")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.167.0")> _
    Public ReadOnly Property [LINETWO]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _linetwo
        End Get
    End Property
    
    ''' <summary>
    ''' Line Three
    ''' </summary>
    <System.ComponentModel.Description("Line Three")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.167.0")> _
    Public ReadOnly Property [LINETHREE]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _linethree
        End Get
    End Property
    
    ''' <summary>
    ''' Line Four
    ''' </summary>
    <System.ComponentModel.Description("Line Four")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.167.0")> _
    Public ReadOnly Property [LINEFOUR]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _linefour
        End Get
    End Property
    
    ''' <summary>
    ''' Line Five
    ''' </summary>
    <System.ComponentModel.Description("Line Five")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.167.0")> _
    Public ReadOnly Property [LINEFIVE]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _linefive
        End Get
    End Property
    
End Class
